name: Run Daily AI Bot

on:
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Get the code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.x'

      - name: Install Gemini SDK
        run: pip install google-genai

      - name: Install image dependencies
        run: pip install requests


      - name: Run Python bot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: python main.py

      - name: Upload daily image
        uses: actions/upload-artifact@v4
        with:
          name: daily-instagram-image
          path: daily_image.png
          
      - name: Save bot memory
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add content_history.json
          git diff --cached --quiet || git commit -m "Update content history"
          git push
